spring:
  datasource:
      url: jdbc:mysql://192.168.99.100:3306/micropass-worksheet?useUnicode=true&characterEncoding=utf8&autoReconnect=true
      username: root
      password: 457420045
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 200
  jpa:
    hibernate:
      ddl-auto: update
  sleuth:
    enabled: true
  zipkin:
    base-url: http://localhost:9151

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9121/eureka/